// Generated by CoffeeScript 1.6.2
var contextMenu, converted, itm, menu, panels, prefSet, save, self, ss, tabs, widget, widgets;

widgets = require("sdk/widget");

tabs = require("sdk/tabs");

self = require("sdk/self");

ss = require("sdk/simple-storage");

panels = require("sdk/panel");

prefSet = require("simple-prefs");

contextMenu = require("sdk/context-menu");

converted = false;

save = {};

if (prefSet.prefs.temperature_unit === "") {
  prefSet.prefs.temperature_unit = "°C";
}

widget = widgets.Widget({
  id: "metrify-button",
  label: "Metrify this Homepage",
  content: "M",
  onClick: function() {
    var tab, worker;

    worker = null;
    if (save[tabs.activeTab.url]) {
      worker = save[tabs.activeTab.url];
    } else {
      worker = tabs.activeTab.attach({
        contentScriptFile: [self.data.url("jquery.min.js"), self.data.url("content_script.js")]
      });
      tab = tabs.activeTab;
      console.log(worker);
      tab.on("ready", function() {
        console.log("Deactivated converted tab");
        return delete save[tab.url];
      });
      save[tabs.activeTab.url] = worker;
      worker.port.emit("setPrefs", prefSet);
    }
    if (converted) {
      worker.port.emit("undo", "all");
    } else {
      if (prefSet.prefs.conv_fahrenheit) {
        worker.port.emit("convert", prefSet.prefs.fahrenheit);
      }
      if (prefSet.prefs.conv_fahrenheit) {
        worker.port.emit("convert", prefSet.prefs.fahrenheit);
      }
    }
    return converted = !converted;
  }
});

menu = contextMenu.Menu({
  label: "Metrifier",
  context: contextMenu.SelectionContext()
});

itm = contextMenu.Item({
  label: "Add to Fahrenheit Strings",
  context: contextMenu.SelectionContext(),
  contentScriptFile: self.data.url('rightclick.js'),
  onMessage: function(text) {
    console.log("Adding", text, "to the string");
    return prefSet.prefs.fahrenheit += "|" + text;
  }
});

menu.addItem(itm);
